services:
  - type: web
    runtime: python
    name: hello-render
    repo: https://github.com/lmmx/hello-render
    region: frankfurt
    plan: free
    buildCommand: sudo ./install_mongod.sh && poetry install
    startCommand: "ls && hello"
