services:
  - type: web
    runtime: python
    name: hello-render
    repo: https://github.com/lmmx/hello-render
    region: frankfurt
    plan: free
    buildCommand: ./install_mongod.sh && poetry install
    startCommand: ./mongodb/bin/mongod --config ./mongodb/mongod.conf --fork && hello
